-- Sufra database: run once in the Supabase SQL editor, then run seed.sql.
-- Catalog tables are public to read; addresses and orders belong to their user (RLS).
-- Orders are created only through place_order(), which prices everything from the database.

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

create table public.categories (
  id text primary key,
  name_ar text not null,
  name_en text not null,
  dot_color text not null default '#00000000', -- #AARRGGBB; transparent hides the dot ("All")
  sort int not null default 0
);

create table public.restaurants (
  id text primary key,
  name_ar text not null,
  name_en text not null,
  cuisine_ar text not null,
  cuisine_en text not null,
  area_ar text not null,
  area_en text not null,
  rating numeric(2, 1) not null default 0,
  rating_count int not null default 0,
  delivery_min int not null,
  delivery_max int not null,
  delivery_fee int not null,          -- shekels
  min_order int not null default 0,   -- shekels
  is_open boolean not null default true,
  category_ids text[] not null default '{}',
  art_index int not null default 0,
  lat double precision not null,
  lng double precision not null,
  sort int not null default 0,
  check (delivery_min <= delivery_max)
);

create table public.menu_sections (
  restaurant_id text not null references public.restaurants on delete cascade,
  id text not null,
  name_ar text not null,
  name_en text not null,
  sort int not null default 0,
  primary key (restaurant_id, id)
);

create table public.products (
  id text primary key,
  restaurant_id text not null references public.restaurants on delete cascade,
  section_id text not null,
  name_ar text not null,
  name_en text not null,
  desc_ar text not null default '',
  desc_en text not null default '',
  price int not null check (price >= 0),
  art_index int not null default 0,
  is_popular boolean not null default false,
  is_available boolean not null default true,
  sort int not null default 0,
  foreign key (restaurant_id, section_id) references public.menu_sections (restaurant_id, id) on delete cascade
);
create index on public.products (restaurant_id);

create table public.option_groups (
  product_id text not null references public.products on delete cascade,
  id text not null,
  name_ar text not null,
  name_en text not null,
  is_required boolean not null default false,
  max_selections int not null default 1 check (max_selections >= 1),
  sort int not null default 0,
  primary key (product_id, id)
);

create table public.option_choices (
  product_id text not null,
  group_id text not null,
  id text not null, -- unique within the product, e.g. 'size.family'
  name_ar text not null,
  name_en text not null,
  price_delta int not null default 0 check (price_delta >= 0),
  sort int not null default 0,
  primary key (product_id, id),
  foreign key (product_id, group_id) references public.option_groups (product_id, id) on delete cascade
);

alter table public.categories enable row level security;
alter table public.restaurants enable row level security;
alter table public.menu_sections enable row level security;
alter table public.products enable row level security;
alter table public.option_groups enable row level security;
alter table public.option_choices enable row level security;

-- Anyone may read the catalog; nobody may write it from the app (edit it from the dashboard).
create policy "catalog is public" on public.categories for select using (true);
create policy "catalog is public" on public.restaurants for select using (true);
create policy "catalog is public" on public.menu_sections for select using (true);
create policy "catalog is public" on public.products for select using (true);
create policy "catalog is public" on public.option_groups for select using (true);
create policy "catalog is public" on public.option_choices for select using (true);

-- ---------------------------------------------------------------------------
-- Per-user data
-- ---------------------------------------------------------------------------

create table public.addresses (
  id text primary key, -- generated by the app, so offline-created addresses keep their id
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  label text not null check (label in ('home', 'work', 'other')),
  lat double precision not null,
  lng double precision not null,
  area_ar text not null,
  area_en text not null,
  landmark text not null check (char_length(landmark) between 3 and 200),
  details text not null default '',
  phone text not null check (phone ~ '^(?:(?:\+|00)97[02]|0)5[69]\d{7}$'),
  created_at timestamptz not null default now()
);
create index on public.addresses (user_id);

alter table public.addresses enable row level security;
create policy "own addresses" on public.addresses for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create table public.orders (
  id bigint generated always as identity (start with 1001) primary key,
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  restaurant_id text not null references public.restaurants,
  -- Snapshots, so an order still reads right after the menu or the address changes.
  restaurant_ar text not null,
  restaurant_en text not null,
  restaurant_lat double precision not null,
  restaurant_lng double precision not null,
  lines jsonb not null,
  address jsonb not null,
  payment text not null default 'cash' check (payment in ('cash')),
  subtotal int not null,
  delivery_fee int not null,
  discount int not null default 0,
  promo_code text,
  eta_min int not null,
  eta_max int not null,
  status text not null default 'placed' check (status in ('placed', 'preparing', 'onTheWay', 'delivered')),
  placed_at timestamptz not null default now()
);
create index on public.orders (user_id, placed_at desc);

alter table public.orders enable row level security;
-- Read only: orders are inserted by place_order() and updated by the restaurant side, never by customers.
create policy "own orders" on public.orders for select using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- place_order: the only way to create an order. Prices come from the database,
-- not the app, so a modified app cannot send its own prices.
--   p_lines: [{"product_id": "...", "quantity": 2, "choice_ids": ["size.family"], "note": "..."}]
-- ---------------------------------------------------------------------------

create or replace function public.place_order(
  p_restaurant_id text,
  p_address_id text,
  p_lines jsonb,
  p_promo_code text default null
) returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_restaurant public.restaurants;
  v_address public.addresses;
  v_line jsonb;
  v_product public.products;
  v_qty int;
  v_note text;
  v_choice_ids text[];
  v_choices jsonb;
  v_unit int;
  v_subtotal int := 0;
  v_lines jsonb := '[]'::jsonb;
  v_discount int := 0;
  v_promo text := null;
  v_group record;
  v_picked int;
  v_order public.orders;
begin
  if v_user is null then
    raise exception 'sign in to order' using errcode = '28000';
  end if;

  select * into v_restaurant from public.restaurants where id = p_restaurant_id;
  if not found then raise exception 'unknown restaurant'; end if;
  if not v_restaurant.is_open then raise exception 'restaurant is closed'; end if;

  select * into v_address from public.addresses where id = p_address_id and user_id = v_user;
  if not found then raise exception 'unknown address'; end if;

  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'empty order';
  end if;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := (v_line ->> 'quantity')::int;
    if v_qty is null or v_qty < 1 or v_qty > 50 then raise exception 'bad quantity'; end if;
    v_note := left(coalesce(v_line ->> 'note', ''), 120);

    select * into v_product from public.products
      where id = v_line ->> 'product_id' and restaurant_id = p_restaurant_id;
    if not found then raise exception 'unknown dish'; end if;
    if not v_product.is_available then raise exception 'dish sold out: %', v_product.id; end if;

    v_choice_ids := array(select jsonb_array_elements_text(coalesce(v_line -> 'choice_ids', '[]'::jsonb)));

    -- Every choice must belong to this dish, and each group's rules must hold.
    if (select count(*) from public.option_choices
          where product_id = v_product.id and id = any (v_choice_ids)) <> cardinality(v_choice_ids) then
      raise exception 'unknown option';
    end if;
    for v_group in select * from public.option_groups where product_id = v_product.id loop
      select count(*) into v_picked from public.option_choices
        where product_id = v_product.id and group_id = v_group.id and id = any (v_choice_ids);
      if v_group.is_required and v_picked = 0 then raise exception 'missing option: %', v_group.id; end if;
      if v_picked > v_group.max_selections then raise exception 'too many options: %', v_group.id; end if;
    end loop;

    select coalesce(jsonb_agg(jsonb_build_object(
             'id', c.id, 'nameAr', c.name_ar, 'nameEn', c.name_en, 'priceDelta', c.price_delta)
             order by g.sort, c.sort), '[]'::jsonb),
           v_product.price + coalesce(sum(c.price_delta), 0)
      into v_choices, v_unit
      from public.option_choices c
      join public.option_groups g on g.product_id = c.product_id and g.id = c.group_id
      where c.product_id = v_product.id and c.id = any (v_choice_ids);

    v_subtotal := v_subtotal + v_unit * v_qty;
    -- Same shape as the app's CartLine JSON.
    v_lines := v_lines || jsonb_build_object(
      'product', jsonb_build_object(
        'id', v_product.id, 'restaurantId', v_product.restaurant_id, 'sectionId', v_product.section_id,
        'nameAr', v_product.name_ar, 'nameEn', v_product.name_en,
        'descAr', v_product.desc_ar, 'descEn', v_product.desc_en,
        'price', v_product.price, 'artIndex', v_product.art_index),
      'quantity', v_qty,
      'choices', v_choices,
      'note', v_note);
  end loop;

  if v_subtotal < v_restaurant.min_order then raise exception 'below minimum order'; end if;

  -- Promo codes live here too, so the app cannot invent discounts. Mirrors lib/features/checkout/promo.dart.
  if upper(trim(coalesce(p_promo_code, ''))) = 'SUFRA20' then
    v_promo := 'SUFRA20';
    v_discount := least(v_subtotal * 20 / 100, 30);
  end if;

  insert into public.orders (
    user_id, restaurant_id, restaurant_ar, restaurant_en, restaurant_lat, restaurant_lng,
    lines, address, subtotal, delivery_fee, discount, promo_code, eta_min, eta_max)
  values (
    v_user, v_restaurant.id, v_restaurant.name_ar, v_restaurant.name_en, v_restaurant.lat, v_restaurant.lng,
    v_lines,
    jsonb_build_object(
      'id', v_address.id, 'label', v_address.label, 'lat', v_address.lat, 'lng', v_address.lng,
      'areaAr', v_address.area_ar, 'areaEn', v_address.area_en, 'landmark', v_address.landmark,
      'details', v_address.details, 'phone', v_address.phone),
    v_subtotal, v_restaurant.delivery_fee, v_discount, v_promo, v_restaurant.delivery_min, v_restaurant.delivery_max)
  returning * into v_order;

  return v_order;
end;
$$;

revoke all on function public.place_order(text, text, jsonb, text) from public, anon;
grant execute on function public.place_order(text, text, jsonb, text) to authenticated;
