// Writes supabase/seed.sql from the app's sample data, so the database and the
// offline demo always hold the same restaurants and menus.
// Run: flutter test tool/export_seed_test.dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:sufra/features/home/data/restaurants_repository.dart';

String q(String s) => "'${s.replaceAll("'", "''")}'";

void main() {
  test('export seed.sql', () async {
    final repo = FakeRestaurantsRepository(delay: Duration.zero);
    final out = StringBuffer()
      ..writeln('-- Generated by tool/export_seed_test.dart — do not edit by hand.')
      ..writeln('-- Run after schema.sql. Safe to re-run: it replaces the catalog.')
      ..writeln('begin;')
      ..writeln('delete from public.restaurants;')
      ..writeln('delete from public.categories;');

    for (final (i, c) in (await repo.fetchCategories()).indexed) {
      final hex = '#${c.dotColor.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}';
      out.writeln('insert into public.categories (id, name_ar, name_en, dot_color, sort) values '
          '(${q(c.id)}, ${q(c.name.ar)}, ${q(c.name.en)}, ${q(hex)}, $i);');
    }

    for (final (i, r) in (await repo.fetchRestaurants()).indexed) {
      out.writeln('insert into public.restaurants (id, name_ar, name_en, cuisine_ar, cuisine_en, area_ar, area_en, '
          'rating, rating_count, delivery_min, delivery_max, delivery_fee, min_order, is_open, category_ids, '
          'art_index, lat, lng, sort) values (${q(r.id)}, ${q(r.name.ar)}, ${q(r.name.en)}, '
          '${q(r.cuisine.ar)}, ${q(r.cuisine.en)}, ${q(r.area.ar)}, ${q(r.area.en)}, ${r.rating}, ${r.ratingCount}, '
          '${r.deliveryMinMinutes}, ${r.deliveryMaxMinutes}, ${r.deliveryFee}, ${r.minOrder}, ${r.isOpen}, '
          "array[${r.categoryIds.map(q).join(', ')}]::text[], ${r.artIndex}, ${r.latitude}, ${r.longitude}, $i);");

      final menu = await repo.fetchMenu(r.id);
      for (final (si, s) in menu.sections.indexed) {
        out.writeln('insert into public.menu_sections (restaurant_id, id, name_ar, name_en, sort) values '
            '(${q(r.id)}, ${q(s.id)}, ${q(s.name.ar)}, ${q(s.name.en)}, $si);');
      }
      for (final (pi, p) in menu.products.indexed) {
        out.writeln('insert into public.products (id, restaurant_id, section_id, name_ar, name_en, desc_ar, desc_en, '
            'price, art_index, is_popular, is_available, sort) values (${q(p.id)}, ${q(p.restaurantId)}, '
            '${q(p.sectionId)}, ${q(p.name.ar)}, ${q(p.name.en)}, ${q(p.description.ar)}, ${q(p.description.en)}, '
            '${p.price}, ${p.artIndex}, ${p.isPopular}, ${p.isAvailable}, $pi);');
        for (final (gi, g) in p.optionGroups.indexed) {
          out.writeln('insert into public.option_groups (product_id, id, name_ar, name_en, is_required, '
              'max_selections, sort) values (${q(p.id)}, ${q(g.id)}, ${q(g.name.ar)}, ${q(g.name.en)}, '
              '${g.isRequired}, ${g.maxSelections}, $gi);');
          for (final (ci, c) in g.choices.indexed) {
            out.writeln('insert into public.option_choices (product_id, group_id, id, name_ar, name_en, '
                'price_delta, sort) values (${q(p.id)}, ${q(g.id)}, ${q(c.id)}, ${q(c.name.ar)}, '
                '${q(c.name.en)}, ${c.priceDelta}, $ci);');
          }
        }
      }
    }
    out.writeln('commit;');
    File('supabase/seed.sql').writeAsStringSync(out.toString());
  });
}
